version: 3.2.{build}
image: Visual Studio 2019
configuration: ReleaseCI
init:
  - git config --global core.autocrlf false
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - ExpressionTreeToString/
    - Shared/

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: nuget restore

matrix:
  fast_finish: true

artifacts:
  - path: Library\bin\ReleaseCI\*.nupkg
    type: NuGetPackage
  - path: Library\bin\ReleaseCI\*.snupkg
    type: NuGetPackage
  - path: TestObjects.VB\bin\Release\*.nupkg
    type: NuGetPackage
  - path: TestObjects.VB\bin\Release\*.snupkg
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: bumZep2HbRvbo8/lMNpoEzEPOU7m7dM9qC+1NRr/kE2BeX8be7tgmGZ5QVpnGmdY
    artifact: /.*(\.|\.s)nupkg/
